<script>
   require([
       "jquery",
       "Magento_Ui/js/modal/modal",
       'mage/backend/notification',
       "prototype"
   ], function(jQuery, modal, notification) {

//<![CDATA[
       Window.keepMultiModalWindow = true;
       var modalView = {
           overlayShowEffectOptions : null,
           overlayHideEffectOptions : null,
           modal: null,
           open : function(viewUrl, elementId, customerEmail) {
               if (viewUrl && elementId && customerEmail) {
                    // elementId = "" //Object.values(elementId)
                    // elementId = JSON.parse(elementId);
                    // console.log(typeof(elementId));
                    // console.log(elementId);
                   data = "<p>Name : <b>"+elementId+ "</b><br/> Email : <b>" + customerEmail+"</b></p>"
                   this.openDialogWindow(data, elementId);

                //    jQuery.ajax({
                //        url: viewUrl,
                //        data: {
                //            id: elementId
                //        },
                //        showLoader: true,
                //        dataType: 'html',
                //        success: function(data, textStatus, transport) {
                //        }.bind(this)
                //    });
               }
           },
           openDialogWindow : function(data, elementId) {
               var self = this;
               if (this.modal) {
                   this.modal.html(jQuery(data).html());
                } else {
                   console.log(data);
                   this.modal = jQuery(data).modal({
                       title: '<?= /* @escapeNotVerified */ __('Detail View'); ?>',
                       modalClass: 'magento',
                       type: 'slide',
                       firedElementId: elementId,
                       buttons: [{
                           text: jQuery.mage.__('Close'),
                           class: 'action- scalable back',
                           click: function () {
                               self.closeDialogWindow(this);
                           }
                       }],
                       close: function () {
                           self.closeDialogWindow(this);
                       }
                   });
               }
               this.modal.modal('openModal');
           },
           closeDialogWindow : function(dialogWindow) {

               jQuery('body').trigger('processStop');
               dialogWindow.closeModal();
               Windows.overlayShowEffectOptions = this.overlayShowEffectOptions;
            //    Windows.overlayHideEffectOptions = this.overlayHideEffectOptions;
           }
       };

       window.modalView = modalView;
//]]>
   });
</script>